{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "ac0d503b_c21b3129",
        "filename": "gnpy/core/info.py",
        "patchSetId": 16
      },
      "lineNbr": 217,
      "author": {
        "id": 1009907
      },
      "writtenOn": "2021-05-25T09:44:25Z",
      "side": 1,
      "message": "Matching errors based on strings looks very fragile to me, but based on a quick glance, there\u0027s nothing better in numpy. Just wanted to say that I\u0027m not convinced that this is an excellent idea, but hey, you wanted to add that for convenience, so be it. If only they had a derived class for that...",
      "revId": "93d858dc715828f3a0fda39d5176608c2dd3430c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "a7cf8cd9_1efdbe0a",
        "filename": "gnpy/core/info.py",
        "patchSetId": 16
      },
      "lineNbr": 217,
      "author": {
        "id": 1017876
      },
      "writtenOn": "2021-05-25T13:32:50Z",
      "side": 1,
      "message": "I totally agree with you on this, unfortunately, as you pointed out, there is no alternative. I have had the matching because I faced a specific case where a ValueError was raised and the dimension mismatch was not the cause. I think that can happen in other situations.",
      "parentUuid": "ac0d503b_c21b3129",
      "revId": "93d858dc715828f3a0fda39d5176608c2dd3430c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "0c879a91_06824f95",
        "filename": "gnpy/core/info.py",
        "patchSetId": 16
      },
      "lineNbr": 217,
      "author": {
        "id": 1009907
      },
      "writtenOn": "2021-05-25T13:47:51Z",
      "side": 1,
      "message": "If you already have a test case for this where the ValueError is not due to an incorrect shape, I would prefer to have that added to the test suite. Not just for a nice 100% test coverage, but also because it looks like a real improvement.",
      "parentUuid": "a7cf8cd9_1efdbe0a",
      "revId": "93d858dc715828f3a0fda39d5176608c2dd3430c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7c3a20e6_26a27127",
        "filename": "gnpy/core/info.py",
        "patchSetId": 16
      },
      "lineNbr": 217,
      "author": {
        "id": 1017876
      },
      "writtenOn": "2021-05-25T14:55:08Z",
      "side": 1,
      "message": "The test case that I had raise an error because there was a bug that I fixed, and that won\u0027t be raised in the current version. I have not other example at the moment, but I cannot assure that a similar behaviour can happen in other cases.",
      "parentUuid": "0c879a91_06824f95",
      "revId": "93d858dc715828f3a0fda39d5176608c2dd3430c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}